from aiogram.types import BotCommand


USER_COMMANDS = [
    BotCommand(command="start", description="Verify & open LMS"),
    BotCommand(command="menu", description="Open LMS"),
    BotCommand(command="trending", description="Trending (private chat)"),
    BotCommand(command="account", description="Account, access & orders"),
    BotCommand(command="referral", description="Referral & rewards"),
    BotCommand(command="study", description="Target, streak & reminders"),
    BotCommand(command="support", description="Support & doubt"),
    BotCommand(command="ask", description="AI Helper"),
    BotCommand(command="community", description="Join Our Community ₹800/month"),
    BotCommand(command="ca", description="CA Tracker Pro ₹200/month"),
]

ADMIN_COMMANDS = [
    BotCommand(command="adminhelp", description="Admin control centre"),
    BotCommand(command="lms", description="LMS access & gate"),
    BotCommand(command="users", description="Users & profiles"),
    BotCommand(command="orders", description="Payments & grants"),
    BotCommand(command="content", description="Courses & sections"),
    BotCommand(command="subscriptions", description="Community & CA plans"),
    BotCommand(command="promo", description="Promo + 12h group broadcast"),
    BotCommand(command="broadcast", description="Broadcast messages"),
    BotCommand(command="schedule", description="Scheduled campaigns"),
    BotCommand(command="inbox", description="Support inbox"),
    BotCommand(command="groups", description="Connected groups/chats"),
    BotCommand(command="referrals", description="Referral audit"),
    BotCommand(command="analytics", description="Analytics"),
    BotCommand(command="ai", description="AI controls"),
    BotCommand(command="presence", description="Admin online/offline"),
    BotCommand(command="security", description="Security posture"),
    BotCommand(command="privacy", description="Privacy audit"),
    BotCommand(command="health", description="Runtime health"),
    BotCommand(command="backup", description="Data backup"),
    BotCommand(command="recovery", description="State recovery"),
    BotCommand(command="moderation", description="Ban/block/antispam"),
    BotCommand(command="resources", description="Resource content"),
    BotCommand(command="notion", description="Notion / CA sync"),
    BotCommand(command="countdown", description="UPSC countdown"),
    BotCommand(command="settings", description="Operational settings"),
    BotCommand(command="audit", description="Event/audit trail"),
    BotCommand(command="export", description="Controlled export"),
    BotCommand(command="system", description="System status"),
    BotCommand(command="lockdown", description="Emergency controls"),
    BotCommand(command="addcourse", description="Add a course with guided setup"),
    BotCommand(command="quickadd", description="Add a course in one command"),
    BotCommand(command="listsectionkeys", description="List section keys"),
    BotCommand(command="grant", description="Grant a course to a user"),
    BotCommand(command="price", description="Update a course price"),
    BotCommand(command="listcourses", description="List active courses"),
    BotCommand(command="listsections", description="List LMS sections"),
    BotCommand(command="userinfo", description="View a user profile"),
    BotCommand(command="activity", description="View user activity"),
    BotCommand(command="contacthistory", description="View user support history"),
    BotCommand(command="pending", description="List pending orders"),
]