"""Full course catalog seed data — see database.py seed_courses(). Regenerate
from the master xlsx if the catalog changes; this file is intentionally just
data, no logic."""

# v6 (Aug 2026) — added a stable batch_id per course (e.g. "CSE-014"), matching
# the # column in Course_Pricing_FINAL.xlsx, so every order notification to
# admin can reference the exact batch. "Paper 1" NET/JRF courses now tag
# net_jrf_all instead of a dedicated net_jrf_paper1 section (merged per request).
# 233 courses, all priced, zero duplicates, verified against Course_Pricing_FINAL.xlsx.
COURSE_SEED = [
    # (name, faculty, medium, notes, price, [section_keys], batch_id)
    ('KGS – Complete BPSC Foundation (Bilingual/Hinglish, NEW)', 'KGS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['bpsc'], 'CSE-001'),
    ('StudyIQ – Agriculture', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_agriculture'], 'CSE-034'),
    ('2026 | 2025 both — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_anthropology'], 'CSE-035'),
    ('2026 — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology'], 'CSE-036'),
    ('2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_anthropology'], 'CSE-037'),
    ('Anthropology Advance 2025 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_anthropology'], 'CSE-038'),
    ('Anthropology Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_anthropology'], 'CSE-039'),
    ('Anthropology QEP+ 2026', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_anthropology'], 'CSE-040'),
    ('Anthropology — Karandeep Sir 2026', 'Levelup IAS', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology'], 'CSE-041'),
    ('CP Kaushik Sir 2027 (ex-Drishti faculty)', 'CP Kaushik Sir', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology'], 'CSE-042'),
    ('DAMP 2025 Levelup IAS', 'Levelup IAS', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['optional_anthropology'], 'CSE-043'),
    ('Harpreet Kukreja 2026 — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology'], 'CSE-044'),
    ('Hima Bindu 2025', 'Hima Bindu', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_anthropology'], 'CSE-045'),
    ('Natraj Sir 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_anthropology'], 'CSE-046'),
    ('Natraj Sir — Anthropology QEP 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_anthropology'], 'CSE-047'),
    ('PW – Anthropology Optional', 'PW', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology'], 'CSE-048'),
    ('Shiva Teja — Anthropology Advance 555 — Ace With Ease', 'Ace With Ease', 'Both', 'Complete course with handouts, lifetime access', 900.0, ['optional_anthropology'], 'CSE-049'),
    ('Sumit Rewri 2027 — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_anthropology'], 'CSE-050'),
    ('Ranker Classes • Study IQ • PW Only IAS', 'Ranker Classes', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_commerce_and_accountancy'], 'CSE-051'),
    ('Bliss Point 2026', 'Bliss Point', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_economics'], 'CSE-052'),
    ('De Facto — 2026 — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_economics'], 'CSE-053'),
    ('PCB 15/16 – Mrunal Sir (Economics)', 'Mrunal', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-218'),
    ('Rishi Jain – Economics (Hindi)', 'Economics (Hindi)', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['optional_economics', 'upsc_subject_specific'], 'CSE-054'),
    ('Shivin Chaudhary – Economics', 'Shivin Chaudhary', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_subject_specific'], 'CSE-225'),
    ('Vibhash Jha 2026 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_economics'], 'CSE-055'),
    ('Sunya IAS • Hornbill • Vajiram & Ravi', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_forestry'], 'CSE-056'),
    ('Crash Course — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_geography'], 'CSE-057'),
    ('Geography Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_geography'], 'CSE-058'),
    ('Geography QEP+ 2026', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_geography'], 'CSE-059'),
    ('Geography QEP+ 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_geography'], 'CSE-060'),
    ('Himanshu Sir — Geography 500+', 'Geography 500+', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_geography'], 'CSE-061'),
    ('Himanshu Sir — Guidance IAS x Sarrthi', 'Guidance IAS x Sarrthi', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_geography'], 'CSE-062'),
    ('Himanshu Thapa — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_geography'], 'CSE-063'),
    ('StudyIQ – Geography Optional', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_geography'], 'CSE-064'),
    ('Vikas Divyakirti Sir • PW Only IAS • Study IQ • KGS', 'PW Only IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_hindi_literature'], 'CSE-065'),
    ('Awadh Ojha Sir (English)', 'Awadh Ojha Sir', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history'], 'CSE-066'),
    ('History Optional 2027 | Sarrthi IAS | Piyush Sir', 'Sarrthi IAS / Piyush Sir', 'Both', 'Complete History Optional batch for CSE 2027', 700.0, ['optional_history'], 'CSE-068'),
    ('History Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history'], 'CSE-069'),
    ('History Optional Crash Course — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_history'], 'CSE-070'),
    ('History Optional – PYQ Course', 'PYQ Course', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_history'], 'CSE-071'),
    ('History QEP cum Crash Course — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_history'], 'CSE-072'),
    ('HISTORY 2027/26', 'KGS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_history'], 'CSE-067'),
    ('Kirthika Mam – Unacademy', 'Unacademy', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history'], 'CSE-073'),
    ('PW – Ahlawat Sir', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history'], 'CSE-074'),
    ('KGS – Mathematics Optional (Bilingual, NEW)', 'KGS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_mathematics'], 'CSE-075'),
    ('Mathocrate — Math Optional • PW — Math Crash Course', 'Mathocrate', 'Both', 'Crash batch', 800.0, ['optional_mathematics'], 'CSE-076'),
    ('Next IAS • PW • Mathocrate • Study IQ • KGS', 'Next IAS', 'Both', 'Main batch', 800.0, ['optional_mathematics'], 'CSE-077'),
    ('Mitra IAS • Tanu Jain • Study IQ • PW • KGS', 'Mitra IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_philosophy'], 'CSE-078'),
    ('Philosophy Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_philosophy'], 'CSE-079'),
    ('Philosophy QEP Mains 2026/2027 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Crash batch', 400.0, ['optional_philosophy'], 'CSE-080'),
    ('Physics Optional Classroom Programme 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_physics'], 'CSE-081'),
    ('2026 / 2024 — Vision IAS / Vajiram & Ravi', 'Vision IAS / Vajiram & Ravi', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_psir'], 'CSE-082'),
    ('Bhartendu Sir 2026 — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir'], 'CSE-083'),
    ('Next IAS 2025', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_psir'], 'CSE-084'),
    ('PSIR QEP — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_psir'], 'CSE-085'),
    ('PSIR — OGP 2026', 'OGP 2026', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_psir'], 'CSE-086'),
    ('PW – Adarsh Sir', 'PW', 'Hindi', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir'], 'CSE-087'),
    ('PW – Eng Bharat Sir', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir'], 'CSE-088'),
    ('Piyush Chaubey Sir 2026|2025 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir'], 'CSE-089'),
    ('Rahul Puri 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_psir'], 'CSE-090'),
    ('Rajesh Mishra', 'Rajesh Mishra', 'Hindi', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir'], 'CSE-091'),
    ('Shashank Tyagi — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir'], 'CSE-092'),
    ('Raus x Anantam IAS • Study IQ', 'Raus x Anantam IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_psychology'], 'CSE-093'),
    ('Lukmaan IAS — Ansari Sir', 'Ansari Sir', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_public_administration'], 'CSE-094'),
    ('PW / Study IQ / KGS — 2026 batches', '2026 batches', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_public_administration'], 'CSE-095'),
    ('Public Administration Optional Classroom Programme 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_public_administration'], 'CSE-096'),
    ('Sarrthi IAS — Ashutosh Pandey', 'Ashutosh Pandey', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_public_administration'], 'CSE-097'),
    ('Sarrthi IAS — Pub Ad QEP', 'Pub Ad QEP', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_public_administration'], 'CSE-098'),
    ('2026 + S Pandey 2025 — PW / Study IQ / KGS', 'PW / Study IQ / KGS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_sociology'], 'CSE-099'),
    ('2026 — Sleepy Classes', 'Sleepy Classes', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_sociology'], 'CSE-100'),
    ('Crash Course + Answer Writing Program — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology'], 'CSE-101'),
    ('Diwakar Bothra 2026|2027 both — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology'], 'CSE-102'),
    ('Nishant Sir 2023', 'Nishant Sir', 'Both', 'Complete course with handouts, lifetime access', 450.0, ['optional_sociology'], 'CSE-103'),
    ('Nishant Sir — Sociology Crash Course 2025', 'Nishant Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_sociology'], 'CSE-104'),
    ('PW – Sociology (Hindi)', 'PW', 'Hindi', 'Complete course with handouts, lifetime access', 800.0, ['optional_sociology'], 'CSE-105'),
    ('Pranay Agrawal 2025|2026|2027 all — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_sociology'], 'CSE-106'),
    ('Pranay Agrawal Sir — Sociology QEP 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_sociology'], 'CSE-107'),
    ('Raj Sir 2026 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology'], 'CSE-108'),
    ('Sarrthi IAS Optional 2027 (Sociology/Anthropology/PSIR)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_sociology', 'optional_anthropology', 'optional_psir'], 'CSE-109'),
    ('Smriti Ma\'am 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_sociology'], 'CSE-110'),
    ('Sociology Crash Course 2025 — Understand UPSC', 'Understand UPSC', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_sociology'], 'CSE-111'),
    ('Sociology — Sleepy Classes Batch 4 2026', 'Sleepy Classes', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_sociology'], 'CSE-112'),
    ('Triumph IAS – Sociology', 'Triumph IAS', 'Both', 'Complete course with handouts, lifetime access', 100.0, ['optional_sociology'], 'CSE-113'),
    ('Vikas Ranjan 2026', 'Vikas Ranjan', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology'], 'CSE-114'),
    ('StudyIQ UPSC + UKPSC', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['ukpsc'], 'CSE-115'),
    ('Study IQ 2026', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['uppsc'], 'CSE-116'),
    ('UPPSC Samagra Batch (Forum IAS)', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['uppsc'], 'CSE-117'),
    ('UPPSC Sarv Saksham Foundation 2026', 'PW', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['uppsc'], 'CSE-118'),
    ('CA Mains 2026 + 2027 Live — Satvik Bhan', 'Satvik Bhan', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ca'], 'CSE-119'),
    ('CA Mains 2026/27 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_ca'], 'CSE-120'),
    ('CA VA Mains 2026 + CA VA Live 2027 both — Dipin Sir', 'Dipin Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_ca'], 'CSE-121'),
    ('Dipin Sir CA-VA (Mains & Prelims)', 'Dipin Sir', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ca'], 'CSE-122'),
    ('Mudit Jain Yearlong CA 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ca'], 'CSE-123'),
    ('Mudit Jain – Current Affairs 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ca'], 'CSE-124'),
    ('Amit Garg CSAT 2027', 'Amit Garg', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-125'),
    ('CSAT 2026 — Hope Tushant', 'Hope Tushant', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-126'),
    ('CSAT 2026 — Sudarshan Lodha', 'Sudarshan Lodha', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-127'),
    ('CSAT 2027 — Amit Garg', 'Amit Garg', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-128'),
    ('CSAT Hindi 2026 — Madhukar Kotwe', 'Madhukar Kotwe', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-129'),
    ('CSAT by IITians 2027 — Sunya IAS', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-130'),
    ('CSAT – Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-131'),
    ('CSAT – Sunya IAS', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-132'),
    ('CSAT — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-133'),
    ('Careerwill – CSAT', 'Careerwill', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-134'),
    ('PW Only IAS 2027 — Rishabh Sharma', 'Rishabh Sharma', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-135'),
    ('PW – Rishab Sir', 'PW', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-136'),
    ('Ram Mohan Pandey – Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-137'),
    ('Sarrthi IAS CSAT 2027', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-138'),
    ('Sunya IAS – CSAT', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-139'),
    ('UNGIST x Sarrthi 2026 — Ram Mohan Pandey Sir', 'Ram Mohan Pandey Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-140'),
    ('Vision IAS – English (With Notes)', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-141'),
    ('Vision IAS – Hindi (Without Notes)', 'Vision IAS', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat'], 'CSE-142'),
    ('Essay (Mudit Jain) 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_essay'], 'CSE-143'),
    ('Forum-IAS Essay Guidance Programme 2026', 'Forum IAS', 'Both', 'Specialized Essay paper guidance, brainstorming & writing practice for Mains 2026', 250.0, ['upsc_essay'], 'CSE-144'),
    ('Shubhra Ranjan – Essay 2026', 'Essay 2026', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_essay'], 'CSE-145'),
    ('Ethics (Mudit Jain) 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ethics'], 'CSE-146'),
    ('Ethics Marks Booster 2026', 'Mudit Jain Sir', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ethics'], 'CSE-147'),
    ('Ethics Samagra (Hindi Medium) — Piyush Sir', 'Piyush Sir', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ethics'], 'CSE-148'),
    ('Ethics by Piyush Sir 2027', 'Piyush Sir', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ethics'], 'CSE-149'),
    ('Lukmaan IAS – Ansari Sir', 'Lukmaan IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_ethics'], 'CSE-150'),
    ('Buniyaad – PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation'], 'CSE-151'),
    ('Forum IAS — GS 2027', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 1200.0, ['upsc_foundation'], 'CSE-152'),
    ('Foundation Course 2026/27 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 1500.0, ['upsc_foundation'], 'CSE-153'),
    ('GS Foundation 2027/28 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation'], 'CSE-154'),
    ('GS Foundation Batch (1/3/4/5/6 — any one)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['upsc_foundation'], 'CSE-155'),
    ('Khan Sir – UPSC Foundation', 'Khan Sir', 'Hindi', 'Complete course with handouts, lifetime access', 850.0, ['upsc_foundation'], 'CSE-156'),
    ('Live/Recorded Foundation 2027/28 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_foundation'], 'CSE-157'),
    ('MagnaCarta Foundation 5 (2027)', 'Atish Mathur', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_foundation'], 'CSE-158'),
    ('Physics Wallah – GS Foundation (Hindi + English)', 'Physics Wallah', 'English', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation'], 'CSE-159'),
    ('Smart Foundation Batch 2027/28/29 — PW OnlyIAS', 'PW OnlyIAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['upsc_foundation'], 'CSE-160'),
    ('Smart Foundation Batch 2027/28/29 — StudyIQ', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['upsc_foundation'], 'CSE-161'),
    ('Unacademy – GS Foundation', 'Unacademy', 'English', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation'], 'CSE-162'),
    ('AWFG 2026', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-163'),
    ('Conquer Mains 2026 (Satyam Jain) — Understand UPSC', 'Understand UPSC', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-164'),
    ('Decode Mains 2026/27 (Mudit Jain) — Combo without CA', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains'], 'CSE-165'),
    ('Decode Mains PRO 2027 — Mudit Jain', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-166'),
    ('Forum IAS MGP 2027', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains'], 'CSE-167'),
    ('Forum-IAS GSAP+ PYQ Anchored Classes For Mains 2026', 'Forum IAS', 'Both', 'GS Augmentation Programme Plus — PYQ-anchored Mains 2026 syllabus coverage & practice', 350.0, ['upsc_mains', 'upsc_pyq'], 'CSE-168'),
    ('LevelUP MMP 2026', 'LevelUp', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_mains'], 'CSE-169'),
    ('M.K. Yadav – QEP 2026', 'M.K. Yadav', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-170'),
    ('MK Yadav QEP & TEP 2026/27', 'MK Yadav', 'Both', 'Complete course with handouts, lifetime access', 450.0, ['upsc_mains'], 'CSE-171'),
    ('MMP+ 2026 (Sarrthi IAS)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_mains'], 'CSE-172'),
    ('MMP+ 2027 (Sarrthi IAS)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains'], 'CSE-173'),
    ('Mains Edge Vision IAS 2026', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-174'),
    ('Mains Excellence Plus — Combo with CA', 'Combo with CA', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_mains'], 'CSE-175'),
    ('Mains QEP 8 — Mrunal Sir', 'Mrunal Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains'], 'CSE-176'),
    ('Nitya Pargati 2027 Batch 3', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-177'),
    ('Sankalp Mains — Sudarshan Lodha', 'Sudarshan Lodha', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-178'),
    ('Shabbir Sir – Essay', 'Essay', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-179'),
    ('Smash Mains 2026', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains'], 'CSE-180'),
    ('Think IAS by Prakash Chitkara (Mains Module)', 'Prakash Chitkara', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_mains'], 'CSE-181'),
    ('Vajiram Sure Shot Mains 2027', 'Vajiram & Ravi', 'Both', 'Dedicated Mains 2027 mentorship & answer writing program', 400.0, ['upsc_mains'], 'CSE-182'),
    ('Write Smart (Shivin Chaudhary)', 'Shivin Chaudhary', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_mains'], 'CSE-183'),
    ('Write Smart + GS-3 Module — Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_mains'], 'CSE-184'),
    ('Dominate Prelims 2026 — Civilsdaily', 'Civilsdaily', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_prelims'], 'CSE-185'),
    ('Fast Track Course 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims'], 'CSE-186'),
    ('Navigator 2026 Batch 1 & 3 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims'], 'CSE-187'),
    ('PMP (Prelims Master Program) — LevelUp IAS', 'LevelUp IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_prelims'], 'CSE-188'),
    ('PRRC + SFG (The Discipline Builder) — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims'], 'CSE-189'),
    ('Prelims Crash Batch — PW OnlyIAS / Target UPSC', 'PW OnlyIAS / Target UPSC', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims'], 'CSE-190'),
    ('Vajiram Power Up Prelims Combo 2027 (GS+CA)', 'Vajiram & Ravi', 'Both', 'Combo batch covering Prelims GS + Current Affairs together', 350.0, ['upsc_prelims', 'upsc_ca'], 'CSE-191'),
    ('Logical Elimination 2026 — Civil Daily IAS', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_pyq'], 'CSE-192'),
    ('PYQ 2026 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq'], 'CSE-193'),
    ('PYQ Edge, UPSC Compass 2026 — Saurabh Arbole Sir', 'Saurabh Arbole Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq'], 'CSE-194'),
    ('Smash PYQ 2026 — Civil Daily IAS', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq'], 'CSE-195'),
    ('Smash PYQ DAW 2026', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq'], 'CSE-196'),
    ('Atish Mathur – GS-2', 'GS-2', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific'], 'CSE-197'),
    ('Bundle: Environment + Economy + Sci-Tech — Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-198'),
    ('Comprehensive Course on Indian Polity 2027 — Sarmad Mehraj Sir', 'Sarmad Mehraj Sir', 'Both', 'Complete foundation course on Indian Polity (GS Paper 2)', 400.0, ['upsc_subject_specific'], 'CSE-199'),
    ('Economics – Jayant Sir', 'Jayant Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-201'),
    ('Economy Module — Shivin Sir', 'Shivin Sir', 'Both', 'Prelims + Foundation both', 250.0, ['upsc_subject_specific'], 'CSE-202'),
    ('Economy PCB15 2026 — Mrunal Sir', 'Mrunal Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-203'),
    ('Economy — Aditya Kaliya Sir', 'Aditya Kaliya Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-204'),
    ('Environment + Geography — Rajesh Govindraj Sir', 'Rajesh Govindraj Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific'], 'CSE-205'),
    ('Environment 2026 — Sudarshan Gujjar', 'Sudarshan Gujjar', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_subject_specific'], 'CSE-206'),
    ('Environment – Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_subject_specific'], 'CSE-207'),
    ('Environment — PMF IAS', 'PMF IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-208'),
    ('Geography – Thapa Sir', 'Thapa Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-209'),
    ('Geography — PMF IAS', 'PMF IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-210'),
    ('Geography — Sudarshan Gujjar', 'Sudarshan Gujjar', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-211'),
    ('Himanshu Thapa – GS Geography', 'GS Geography', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-212'),
    ('History 2026 — Prateek Nayak', 'Prateek Nayak', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-213'),
    ('International Relations — Chetan Sir', 'Chetan Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-214'),
    ('MCF 4 + MCMA 2026 — Atish Mathur', 'Atish Mathur', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific'], 'CSE-215'),
    ('MCPA Prelims Magna Carta 2026 — Atish Mathur', 'Atish Mathur', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-216'),
    ('Mrunal – PCB 12/13/14', 'Mrunal', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_subject_specific'], 'CSE-217'),
    ('PMF – Environment', 'Environment', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-219'),
    ('PW – Indian Society & Social Justice', 'PW', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-220'),
    ('Polity & Governance — Sidharth Arora', 'Sidharth Arora', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-221'),
    ('ECONOMICS FOUNDATION', 'Basava Uppin', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific'], 'CSE-200'),
    ('Sci & Tech – Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_subject_specific'], 'CSE-222'),
    ('Sci-Tech + Environment — CP Kaushik Sir', 'CP Kaushik Sir', 'Both', 'ex-Drishti IAS faculty', 350.0, ['upsc_subject_specific'], 'CSE-223'),
    ('Sci-Tech + Environment — Ravi Agrahari Sir', 'Ravi Agrahari Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific'], 'CSE-224'),
    ('Shivin Chaudhary – Environment & S&T', 'Shivin Chaudhary', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_subject_specific'], 'CSE-226'),
    ('Sudarshan Gurjar – Environment & Ecology', 'Environment & Ecology', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific'], 'CSE-227'),
    ('MGP Mains 2026 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ts_mains', 'upsc_mains'], 'CSE-228'),
    ('MGP Prime 2027 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ts_mains', 'upsc_mains'], 'CSE-229'),
    ('Mains Test Series Bundle 2027', 'Multi-institute Bundle', 'Both', 'Includes test series from: Forum IAS, Vision IAS, Vajiram & Ravi, Drishti IAS, Next IAS, Sarrthi IAS, PW Only IAS, Study IQ & more', 1000.0, ['upsc_ts_mains'], 'CSE-230'),
    ('PTS 2027 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ts_prelims'], 'CSE-231'),
    ('PTS 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ts_prelims'], 'CSE-232'),
    ('Prelims Test Series Bundle 2027', 'Multi-institute Bundle', 'Both', 'Includes test series from: Forum IAS, Vision IAS, Vajiram & Ravi, Drishti IAS, Next IAS, Sarrthi IAS, PW Only IAS, Study IQ & more', 700.0, ['upsc_ts_prelims'], 'CSE-233'),
    ('IFAS – All Subject', 'IFAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['net_jrf_all'], 'CSE-002'),
    ('PW – Paper 1 & History', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['net_jrf_all'], 'CSE-003'),
    ('UGC NET JRF December 2026 — Commerce', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_commerce'], 'CSE-004'),
    ('UGC NET JRF June 2027 — Commerce', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_commerce'], 'CSE-005'),
    ('UGC NET JRF December 2026 — Computer Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_computer_science'], 'CSE-006'),
    ('UGC NET JRF June 2027 — Computer Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_computer_science'], 'CSE-007'),
    ('UGC NET JRF December 2026 — Education', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_education'], 'CSE-008'),
    ('UGC NET JRF June 2027 — Education', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_education'], 'CSE-009'),
    ('UGC NET JRF December 2026 — English', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_english'], 'CSE-010'),
    ('UGC NET JRF June 2027 — English', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_english'], 'CSE-011'),
    ('UGC NET JRF December 2026 — Geography', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_geography'], 'CSE-012'),
    ('UGC NET JRF June 2027 — Geography', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_geography'], 'CSE-013'),
    ('UGC NET JRF December 2026 — History', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_history'], 'CSE-014'),
    ('UGC NET JRF June 2027 — History', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_history'], 'CSE-015'),
    ('UGC NET JRF December 2026 — Home Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_home_science'], 'CSE-016'),
    ('UGC NET JRF June 2027 — Home Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_home_science'], 'CSE-017'),
    ('UGC NET JRF December 2026 — Law', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_law'], 'CSE-018'),
    ('UGC NET JRF June 2027 — Law', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_law'], 'CSE-019'),
    ('UGC NET JRF December 2026 — Management', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_management'], 'CSE-020'),
    ('UGC NET JRF June 2027 — Management', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_management'], 'CSE-021'),
    ('UGC NET JRF December 2026 — Paper 1', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_all'], 'CSE-022'),
    ('UGC NET JRF June 2027 — Paper 1', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_all'], 'CSE-023'),
    ('UGC NET JRF December 2026 — Philosophy', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_philosophy'], 'CSE-024'),
    ('UGC NET JRF June 2027 — Philosophy', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_philosophy'], 'CSE-025'),
    ('UGC NET JRF December 2026 — Polity', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_polity'], 'CSE-026'),
    ('UGC NET JRF June 2027 — Polity', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_polity'], 'CSE-027'),
    ('UGC NET JRF December 2026 — Psychology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_psychology'], 'CSE-028'),
    ('UGC NET JRF June 2027 — Psychology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_psychology'], 'CSE-029'),
    ('UGC NET JRF December 2026 — Public Administration', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_public_administration'], 'CSE-030'),
    ('UGC NET JRF June 2027 — Public Administration', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_public_administration'], 'CSE-031'),
    ('UGC NET JRF December 2026 — Sociology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_sociology'], 'CSE-032'),
    ('UGC NET JRF June 2027 — Sociology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_sociology'], 'CSE-033'),
]
