"""Single LMS Mini App shell: course catalog + paid CA Tracker Pro + Community dashboard."""
import html
from datetime import datetime
import config

BASE = config.WEBAPP_BASE_URL.rstrip("/")

SHELL = """<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1,viewport-fit=cover'><title>{title}</title><script src='https://telegram.org/js/telegram-web-app.js'></script><style>
:root{{--bg:var(--tg-theme-bg-color,#f7f7fb);--card:var(--tg-theme-secondary-bg-color,#fff);--text:var(--tg-theme-text-color,#111);--hint:var(--tg-theme-hint-color,#777);--accent:var(--tg-theme-button-color,#2aabee)}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font:14px system-ui,-apple-system,sans-serif;padding:14px}}header{{position:sticky;top:0;background:var(--bg);z-index:5;padding:6px 0 12px}}h1{{font-size:20px;margin:4px 0}}.sub{{color:var(--hint);font-size:12px}}.toolbar{{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}}input,select,button{{font:inherit}}input,select{{padding:10px;border:1px solid #ddd;border-radius:12px;background:var(--card);color:var(--text)}}button{{border:0;border-radius:12px;padding:9px 12px;background:var(--accent);color:#fff}}.secondary{{background:var(--card);color:var(--text);border:1px solid #ddd}}.grid{{display:grid;gap:10px}}.card{{background:var(--card);border-radius:16px;padding:13px;box-shadow:0 2px 9px #00000010}}.title{{font-weight:700;margin-bottom:5px}}.meta{{color:var(--hint);font-size:12px;line-height:1.45}}.row{{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:9px}}.price{{font-weight:700}}.chips{{display:flex;gap:6px;flex-wrap:wrap}.chip{{border-radius:999px;padding:6px 9px;background:var(--card);border:1px solid #ddd;font-size:12px}}.content{{max-width:100%;line-height:1.6}}.zoom{{display:flex;gap:6px;align-items:center}}.small{{font-size:12px}}.empty{{padding:30px 8px;text-align:center;color:var(--hint)}}a{{color:var(--accent)}}</style></head><body><header><h1>{title}</h1><div class='sub'>{subtitle}</div><div id='liveCountdown' class='small'></div></header>{body}<script>const tg=window.Telegram.WebApp;tg.ready();tg.expand();const init=tg.initData||'';const examDate='{exam_date}';function tick(){{const d=new Date(examDate+'T00:00:00+05:30').getTime()-Date.now();const el=document.getElementById('liveCountdown');if(el)el.textContent=d>0?'⏳ Live countdown: '+Math.floor(d/86400000)+'d '+Math.floor(d%86400000/3600000)+'h '+Math.floor(d%3600000/60000)+'m '+Math.floor(d%60000/1000)+'s':'Exam date reached';}}setInterval(tick,1000);tick();async function api(path,opt={{}}){{opt.headers={{...(opt.headers||{{}}), 'X-Init-Data':init}};return fetch(path,opt)}}function go(path){{location.href=path}}</script></body></html>"""


def render_lms() -> str:
    body="""<div class='toolbar'><input id='q' placeholder='Search courses / faculty' style='flex:1'><select id='section'><option value='all'>All</option></select></div><div class='chips' id='sections'></div><div id='list' class='grid'></div><div id='empty' class='empty' hidden>No courses found.</div><script>
let rows=[];let section='all';async function loadSections(){let r=await api('/api/lms/sections');if(r.ok){let d=await r.json();let s=document.getElementById('section');d.forEach(x=>{let o=document.createElement('option');o.value=x.key;o.textContent=x.name;s.appendChild(o)})}}async function load(){let s=document.getElementById('section').value;let r=await api('/api/courses?section_key='+encodeURIComponent(s));if(r.status===403){document.getElementById('list').innerHTML='<div class=empty>Access required. Verify your number first.</div>';return}rows=await r.json();render()}function render(){let q=document.getElementById('q').value.toLowerCase();let a=rows.filter(c=>!q||c.name.toLowerCase().includes(q)||(c.faculty||'').toLowerCase().includes(q));let el=document.getElementById('list');el.innerHTML='';document.getElementById('empty').hidden=!!a.length;a.forEach(c=>{let d=document.createElement('div');d.className='card';let action=c.included?'<span class=price>✅ Included</span>':'<span class=price>'+(c.price==null?'Price on request':'₹'+c.price)+'</span><button onclick="buy('+c.id+')">Buy</button>';d.innerHTML='<div class=title>'+esc(c.name)+'</div><div class=meta>'+esc(c.faculty||'')+' · '+esc(c.medium||'')+'</div><div class=row>'+action+'</div>';el.appendChild(d)})}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}async function buy(id){let r=await api('/api/course-link/'+id);let d=await r.json();if(d.url)tg.openTelegramLink(d.url)}document.getElementById('q').oninput=render;document.getElementById('section').onchange=load;loadSections().then(load);
</script>"""
    return SHELL.format(title="📚 LMS",subtitle="All course listings stay inside this Mini App.",body=body,exam_date=config.EXAM_DATE)


def render_ca() -> str:
    body="""<div class='card'><b>CA TRACKER PRO by Professor 🥼</b><div class='meta'>⭐ 4.5/5 · 50 users · ₹200/month</div><div class='zoom' style='margin-top:8px'><button class=secondary onclick='zoom(-1)'>A−</button><span id='zs'>100%</span><button class=secondary onclick='zoom(1)'>A+</button><button class=secondary onclick='resetZoom()'>Reset</button></div></div><div class='toolbar'><button onclick=load('all')>All</button><button class=secondary onclick=load('daily')>Daily CA</button><button class=secondary onclick=load('editorial')>Editorial</button><button class=secondary onclick=load('place_news')>Place in News</button><button class=secondary onclick=load('international')>International Organisations</button></div><div class='toolbar'><input id='q' placeholder='Search article/topic/organisation' style='flex:1'><input id='topic' placeholder='Topic filter'><input id='date' type='date'><button onclick='load(current)'>Filter</button></div><div id='list' class='grid'></div><script>let size=100,current='all',rows=[];async function load(dataset){current=dataset;let url=dataset==='all'?'/api/ca/items':'/api/ca/dataset/'+dataset;let r=await api(url+'?source=all&topic='+encodeURIComponent(topic.value)+'&date='+encodeURIComponent(date.value)+'&q='+encodeURIComponent(q.value));if(r.status===403){list.innerHTML='<div class=empty>CA Tracker Pro subscription required.</div>';return}rows=await r.json();render()}function render(){let el=document.getElementById('list');el.innerHTML='';(rows||[]).forEach(x=>{let d=document.createElement('div');d.className='card content';d.style.fontSize=size+'%';d.innerHTML='<div class=title>'+esc(x.title)+'</div><div class=meta>'+esc(x.source)+' · '+esc(x.date)+' · '+esc(x.topic)+'</div><p>'+esc(x.summary||'')+'</p>'+(x.location?'<div class=chips><span class=chip>📍 '+esc(x.location)+'</span></div>':'')+(x.organisation?'<div class=chips><span class=chip>🏛 '+esc(x.organisation)+'</span></div>':'')+(x.url?'<a href="'+esc(x.url)+'" target="_blank">Open source</a>':'');el.appendChild(d)})}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function zoom(d){size=Math.max(70,Math.min(180,size+d*10));applyZoom()}function resetZoom(){size=100;applyZoom()}function applyZoom(){zs.textContent=size+'%';document.querySelectorAll('.content').forEach(x=>x.style.fontSize=size+'%')}load('all');</script>"""
    return SHELL.format(title="📰 CA TRACKER PRO by Professor 🥼",subtitle="The Hindu · Indian Express · PIB Daily · Editorials · Place in News · International Organisations",body=body,exam_date=config.EXAM_DATE)


def render_community() -> str:
    body="""<div class='card'><div class='title'>👥 Join Our Community</div><div class='meta'>₹800/month · all courses · personal AI tracking · answer evaluation</div></div><div id='dashboard' class='grid'><div class='card'>Loading personal AI tracking…</div></div><div class='card'><div class=title>Answer Evaluation</div><textarea id='ans' placeholder='Paste your answer here' rows='7' style='width:100%;padding:10px;border-radius:12px;border:1px solid #ddd'></textarea><button style='margin-top:8px' onclick='evalAns()'>Evaluate</button><div id='out' class=content></div></div><script>async function load(){let r=await api('/api/community/dashboard');if(r.status===403){dashboard.innerHTML='<div class=empty>Community subscription required.</div>';return}let d=await r.json();dashboard.innerHTML='<div class=card><div class=title>Personal AI Tracking</div><div class=meta>Activity: '+d.activity+' · AI questions: '+d.ai_questions+' · Streak: '+d.streak+'</div></div>'}async function evalAns(){let r=await api('/api/community/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer:ans.value})});let d=await r.json();out.innerText=d.feedback||d.error||'Unable to evaluate';}load();</script>"""
    return SHELL.format(title="👥 Join Our Community",subtitle="Private member dashboard",body=body,exam_date=config.EXAM_DATE)
